import { motion } from 'framer-motion'
import { ArrowRight, BellRing, BookOpen, Check, Cloud, MessageCircle, PackageCheck, ShieldCheck, ShoppingBag, Smartphone, Users, WalletCards } from 'lucide-react'
import { Link } from 'react-router-dom'
import { legalLinks } from '../lib/legal'

const products = [
  { icon: BookOpen, title: 'Fiados', text: 'Sabe quién te debe, cuánto y desde cuándo. Cobra por WhatsApp en un toque.', color: 'bg-sky' },
  { icon: PackageCheck, title: 'Apartados', text: 'Controla abonos, saldos y fechas límite sin perder mercancía de vista.', color: 'bg-lilac' },
  { icon: WalletCards, title: 'Caja', text: 'Registra lo que entra y sale. Al final del día sabrás cuánto debería haber.', color: 'bg-lime' },
  { icon: ShoppingBag, title: 'Pedidos', text: 'Organiza lo pendiente, lo que estás preparando y lo que ya puede entregarse.', color: 'bg-peach' },
]

export function Landing() {
  return (
    <div className="min-h-screen overflow-hidden bg-cream text-ink">
      <header className="relative z-20 mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8 lg:px-10">
        <Link to="/" className="text-2xl font-black tracking-tight"><span className="text-coral">Mi</span> Libreta</Link>
        <nav className="hidden items-center gap-8 text-sm font-extrabold text-ink/55 md:flex"><a href="#productos" className="hover:text-ink">Lo que incluye</a><a href="#como-funciona" className="hover:text-ink">Cómo funciona</a><a href="#precio" className="hover:text-ink">Precio</a></nav>
        <div className="flex items-center gap-2"><Link to="/iniciar-sesion" className="hidden rounded-full px-4 py-2.5 text-sm font-black sm:block">Entrar</Link><Link to="/registro" className="rounded-full bg-ink px-4 py-2.5 text-sm font-black text-white shadow-soft sm:px-5">Probar gratis</Link></div>
      </header>

      <main>
        <section className="relative mx-auto grid max-w-7xl items-center gap-12 px-5 pb-20 pt-14 sm:px-8 sm:pt-20 lg:grid-cols-[1.05fr_.95fr] lg:px-10 lg:pb-28 lg:pt-24">
          <div className="relative z-10 max-w-2xl">
            <motion.p initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} className="inline-flex items-center gap-2 rounded-full bg-white px-4 py-2 text-xs font-black uppercase tracking-[0.13em] shadow-soft"><span className="size-2 rounded-full bg-coral" /> Hecha para negocios de barrio</motion.p>
            <motion.h1 initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .06 }} className="mt-6 text-5xl font-black leading-[.96] tracking-[-0.055em] sm:text-7xl lg:text-[5.2rem]">Tu negocio,<br /><span className="text-coral">bien apuntado.</span></motion.h1>
            <motion.p initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .12 }} className="mt-6 max-w-xl text-lg font-semibold leading-relaxed text-ink/55 sm:text-xl">Fiados, apartados, pedidos, clientes y caja sin cuentas complicadas. Tan fácil como tu libreta, pero te ayuda a cobrar y no se pierde.</motion.p>
            <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .18 }} className="mt-8 flex flex-col gap-3 sm:flex-row"><Link to="/registro" className="flex items-center justify-center gap-2 rounded-2xl bg-ink px-6 py-4 font-black text-white shadow-card">Empieza gratis <ArrowRight size={19} /></Link><a href="#productos" className="flex items-center justify-center rounded-2xl bg-white px-6 py-4 font-black shadow-soft">Ver lo que hace</a></motion.div>
            <p className="mt-5 flex items-center gap-2 text-sm font-bold text-ink/40"><ShieldCheck size={18} className="text-[#168c5b]" /> Sin tarjeta · Cancela cuando quieras</p>
          </div>

          <motion.div initial={{ opacity: 0, x: 30, rotate: 2 }} animate={{ opacity: 1, x: 0, rotate: -1 }} transition={{ delay: .12, type: 'spring', damping: 22 }} className="relative mx-auto w-full max-w-lg">
            <div className="absolute -inset-12 -z-10 rounded-full bg-lime/45 blur-3xl" />
            <div className="rounded-[2.4rem] bg-ink p-4 shadow-[0_35px_80px_rgba(29,41,34,.28)] sm:p-5">
              <div className="rounded-[1.8rem] bg-cream p-5 sm:p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-[.14em] text-coral">Abarrotes Lupita</p><p className="mt-1 text-xl font-black">Buenos días, Luisa</p></div><span className="grid size-10 place-items-center rounded-full bg-lime font-black">L</span></div><div className="mt-5 rounded-[1.5rem] bg-white p-5 shadow-soft"><p className="text-xs font-bold text-ink/40">Te deben entre todos</p><p className="mt-1 text-3xl font-black">$6,840</p><div className="mt-5 border-t border-ink/8 pt-4"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-full bg-peach font-black">M</span><div className="flex-1"><p className="text-sm font-black">María Hernández</p><p className="text-xs font-semibold text-ink/40">Sin abonar hace 43 días</p></div><p className="font-black">$850</p></div><button className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl bg-[#dff7e9] px-4 py-3 text-sm font-black text-[#168c5b]"><MessageCircle size={17} /> Recordar por WhatsApp</button></div></div><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-lime p-4"><p className="text-xs font-bold text-ink/45">Entró hoy</p><p className="mt-1 text-xl font-black">+$2,840</p></div><div className="rounded-2xl bg-peach p-4"><p className="text-xs font-bold text-ink/45">Salió hoy</p><p className="mt-1 text-xl font-black">−$850</p></div></div></div>
            </div>
            <div className="absolute -bottom-5 -left-4 flex items-center gap-2 rounded-full bg-white px-4 py-3 text-sm font-black shadow-card sm:-left-10"><span className="grid size-7 place-items-center rounded-full bg-lime"><Check size={15} /></span> Abono guardado</div>
          </motion.div>
        </section>

        <section id="productos" className="bg-white py-20 sm:py-24"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10"><div className="max-w-2xl"><p className="text-xs font-black uppercase tracking-[.16em] text-coral">Todo en un solo lugar</p><h2 className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">Lo que tu libreta no puede hacer por ti</h2></div><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{products.map(({ icon: Icon, title, text, color }) => <article key={title} className={`${color} rounded-[2rem] p-6 sm:p-7`}><span className="grid size-12 place-items-center rounded-2xl bg-white/70"><Icon size={23} /></span><h3 className="mt-8 text-2xl font-black">{title}</h3><p className="mt-2 font-semibold leading-relaxed text-ink/55">{text}</p></article>)}</div><article className="mt-4 flex flex-col gap-5 rounded-[2rem] bg-cream p-6 sm:flex-row sm:items-center sm:p-7"><span className="grid size-12 shrink-0 place-items-center rounded-2xl bg-white"><Users size={23} /></span><div className="flex-1"><h3 className="text-xl font-black">Clientes en una sola ficha</h3><p className="mt-1 font-semibold text-ink/50">Guarda teléfono, dirección y notas; consulta sus fiados, apartados y pedidos juntos.</p></div></article></div></section>

        <section id="como-funciona" className="py-20 sm:py-28"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-start"><div className="lg:sticky lg:top-10"><p className="text-xs font-black uppercase tracking-[.16em] text-coral">Sin manuales ni cursos</p><h2 className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">Si sabes usar WhatsApp, sabes usar Mi Libreta.</h2><p className="mt-5 font-semibold leading-relaxed text-ink/50">No hay palabras contables ni formularios eternos. Apuntas, guardas y sigues atendiendo.</p><Link to="/registro" className="mt-7 inline-flex items-center gap-2 rounded-2xl bg-ink px-6 py-4 font-black text-white">Crear mi libreta <ArrowRight size={18} /></Link></div><div className="space-y-4">{[
                ['01', 'Elige lo que necesitas', 'Activa Fiados, Apartados o Caja. Tu aplicación mostrará sólo las herramientas que uses.'],
                ['02', 'Apunta en segundos', 'Registra una venta, un gasto o un nuevo fiado con la menor cantidad de pasos posible.'],
                ['03', 'La app hace las cuentas', 'Ve saldos, atrasos y lo que debería haber en caja sin buscar hojas ni usar calculadora.'],
              ].map(([number, title, text]) => <article key={number} className="flex gap-5 rounded-[2rem] bg-white p-6 shadow-soft sm:p-8"><span className="text-3xl font-black text-coral/30">{number}</span><div><h3 className="text-xl font-black">{title}</h3><p className="mt-2 font-semibold leading-relaxed text-ink/50">{text}</p></div></article>)}</div></div></div></section>

        <section className="mx-4 overflow-hidden rounded-[2.5rem] bg-ink py-20 text-white sm:mx-6 sm:rounded-[3rem] lg:mx-8"><div className="mx-auto grid max-w-6xl items-center gap-12 px-6 sm:px-10 lg:grid-cols-2"><div><p className="text-xs font-black uppercase tracking-[.16em] text-lime">Tu memoria ya puede descansar</p><h2 className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">La app te dice qué necesita tu atención.</h2><p className="mt-5 font-semibold leading-relaxed text-white/55">Abre por la mañana y encuentra a quién cobrarle, qué apartado está por vencer y cómo va tu caja.</p><div className="mt-8 space-y-4">{[[BellRing, 'Alertas de clientes que llevan mucho sin abonar'], [MessageCircle, 'Mensajes de cobro listos para WhatsApp'], [Cloud, 'Respaldo para que tu información no se pierda'], [Smartphone, 'Funciona desde el teléfono que ya tienes']].map(([Icon, text]) => <p key={text as string} className="flex items-center gap-3 font-bold text-white/75"><span className="grid size-10 shrink-0 place-items-center rounded-full bg-white/10"><Icon size={19} className="text-lime" /></span>{text as string}</p>)}</div></div><div className="rounded-[2rem] bg-white p-5 text-ink shadow-card sm:p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-[.14em] text-coral">Atención</p><h3 className="mt-1 text-2xl font-black">A quién cobrarle</h3></div><span className="rounded-full bg-peach px-3 py-1 text-xs font-black">3 pendientes</span></div>{[['María', '43 días', '$850'], ['Juan', '31 días', '$620'], ['Rosa', 'Paga hoy', '$430']].map(([name, time, amount], index) => <div key={name} className={`flex items-center gap-3 py-4 ${index ? 'border-t border-ink/8' : 'mt-4'}`}><span className={`grid size-10 place-items-center rounded-full ${index === 2 ? 'bg-lime' : 'bg-peach'} font-black`}>{name[0]}</span><div className="flex-1"><p className="font-black">{name}</p><p className="text-xs font-semibold text-ink/40">{time === 'Paga hoy' ? time : `Sin abonar hace ${time}`}</p></div><p className="font-black">{amount}</p></div>)}</div></div></section>

        <section id="precio" className="py-20 sm:py-28"><div className="mx-auto max-w-5xl px-5 text-center sm:px-8"><p className="text-xs font-black uppercase tracking-[.16em] text-coral">Un precio sin letras chiquitas</p><h2 className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">Que se pague sola con un fiado recuperado.</h2><div className="mx-auto mt-10 max-w-xl rounded-[2.3rem] bg-white p-6 text-left shadow-card sm:p-9"><div className="flex flex-col justify-between gap-4 border-b border-ink/8 pb-7 sm:flex-row sm:items-end"><div><p className="text-sm font-black text-ink/40">Mi Libreta completa</p><p className="mt-2 text-5xl font-black">$79<span className="text-base text-ink/35"> / mes</span></p></div><span className="w-fit rounded-full bg-lime px-4 py-2 text-xs font-black">Primer mes gratis</span></div><div className="mt-6 grid gap-3 sm:grid-cols-2">{['Fiados y abonos ilimitados', 'Apartados y vencimientos', 'Pedidos por estado', 'Directorio de clientes', 'Caja diaria', 'Recordatorios por WhatsApp', 'Respaldo en la nube', 'Configura sólo lo que usas'].map((item) => <p key={item} className="flex items-center gap-2 text-sm font-bold"><Check size={17} className="text-[#168c5b]" />{item}</p>)}</div><Link to="/registro" className="mt-7 flex items-center justify-center gap-2 rounded-2xl bg-coral px-6 py-4 font-black text-white">Probar gratis <ArrowRight size={18} /></Link><p className="mt-3 text-center text-xs font-semibold text-ink/35">Sin tarjeta. Cancela cuando quieras.</p></div></div></section>

        <section className="bg-white py-20"><div className="mx-auto max-w-4xl px-5 sm:px-8"><div className="text-center"><p className="text-xs font-black uppercase tracking-[.16em] text-coral">Preguntas frecuentes</p><h2 className="mt-3 text-4xl font-black tracking-tight">Antes de empezar</h2></div><div className="mt-10 grid gap-4 sm:grid-cols-2">{[
          ['¿Necesito computadora?', 'No. Mi Libreta está pensada para usarse desde tu teléfono Android o iPhone.'],
          ['¿Tiene que ver con el SAT?', 'No. No hacemos facturación ni contabilidad fiscal. Es una herramienta para organizar tu negocio.'],
          ['¿Qué pasa si pierdo mi teléfono?', 'Inicias sesión desde otro teléfono y tu información respaldada vuelve a aparecer.'],
          ['¿Tengo que usar todo?', 'No. Durante el registro eliges Fiados, Apartados, Caja o Pedidos y puedes cambiarlo después.'],
        ].map(([question, answer]) => <article key={question} className="rounded-[1.7rem] bg-cream p-6"><h3 className="font-black">{question}</h3><p className="mt-2 text-sm font-semibold leading-relaxed text-ink/50">{answer}</p></article>)}</div></div></section>
      </main>
      <footer className="bg-ink px-5 py-10 text-white sm:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-6"><div className="flex flex-col items-center justify-between gap-5 sm:flex-row"><Link to="/" className="text-2xl font-black"><span className="text-coral">Mi</span> Libreta</Link><p className="text-sm font-semibold text-white/35">Tu negocio, bien apuntado.</p><div className="flex gap-5 text-sm font-bold text-white/55"><Link to="/iniciar-sesion">Entrar</Link><Link to="/registro">Crear cuenta</Link></div></div><div className="flex flex-wrap justify-center gap-x-5 gap-y-2 border-t border-white/10 pt-5 text-xs font-bold text-white/40 sm:justify-start">{legalLinks.map((item) => <Link key={item.to} to={item.to} className="hover:text-white">{item.label}</Link>)}</div></div></footer>
    </div>
  )
}
