import { LegalLayout, LegalSection } from '../components/LegalLayout'
import { legalConfig } from '../lib/legal'

export function Payments() {
  return <LegalLayout eyebrow="Suscripciones" title="Pagos y cancelaciones" summary="Cada libreta tiene su propia prueba y suscripción. Aquí explicamos cuándo se cobra, cómo cancelar y cuándo procede un reembolso.">
    <LegalSection title="1. Prueba gratuita"><p>Cada libreta elegible comienza con la duración de prueba mostrada al crearla, sin solicitar tarjeta. Al terminar, el acceso puede restringirse si no existe una suscripción o permiso administrativo vigente. Crear nuevas cuentas o libretas para eludir los límites de prueba está prohibido.</p></LegalSection>
    <LegalSection title="2. Precio y cobro recurrente"><p>Antes de contratar, Stripe muestra el precio total, moneda, impuestos aplicables, periodicidad y fecha de cobro. La suscripción corresponde sólo a la libreta seleccionada y se renueva automáticamente por periodos mensuales hasta su cancelación. El cobro recurrente requiere tu confirmación expresa durante el pago.</p></LegalSection>
    <LegalSection title="3. Renovación"><p>La fecha del siguiente cobro y el estado de la suscripción pueden consultarse desde Configuración y el portal de Stripe. Cuando corresponda una renovación automática, se deberá comunicar el aviso previo exigido por la legislación aplicable y permitir la cancelación sin penalización.</p></LegalSection>
    <LegalSection title="4. Cancelación inmediata"><p>Puedes solicitar la cancelación en cualquier momento desde <strong>Dashboard → Configuración → Administrar en Stripe</strong>. La solicitud detiene inmediatamente la renovación automática y no genera penalización. Salvo que la ley o la pantalla de cancelación indique otra cosa, conservarás el acceso hasta que termine el periodo ya pagado.</p><p>Eliminar la aplicación, cerrar sesión o dejar de usar una libreta no cancela por sí solo la suscripción.</p></LegalSection>
    <LegalSection title="5. Reembolsos"><p>Por regla general, los periodos ya iniciados no se reembolsan de forma proporcional. Revisaremos solicitudes por cobros duplicados, no autorizados, errores técnicos que impidan prestar el servicio o cualquier supuesto exigido por la legislación de protección al consumidor. Cuando proceda, el reembolso se realizará al mismo medio de pago, salvo autorización expresa para usar otro.</p></LegalSection>
    <LegalSection title="6. Pagos fallidos"><p>Si un pago falla, Stripe podrá reintentar el cobro y la suscripción puede pasar a estado pendiente, impagado o cancelado. El acceso podrá restringirse conforme al estado de la suscripción. Puedes actualizar el método de pago desde el portal de Stripe.</p></LegalSection>
    <LegalSection title="7. Aclaraciones"><p>Para cancelar, solicitar un reembolso o aclarar un cargo, escribe a <strong>{legalConfig.supportEmail}</strong> o llama al <strong>{legalConfig.phone}</strong>. Incluye el correo de tu cuenta, la libreta afectada, fecha y descripción del cargo; nunca envíes el número completo de tu tarjeta ni su código de seguridad.</p></LegalSection>
  </LegalLayout>
}
