import { LegalLayout, LegalSection } from '../components/LegalLayout'
import { legalConfig } from '../lib/legal'

export function Privacy() {
  return <LegalLayout eyebrow="Protección de datos" title="Aviso de privacidad integral" summary="Aquí explicamos qué datos trata Mi Libreta, para qué los usa y cómo puedes ejercer tus derechos sobre ellos.">
    <LegalSection title="1. Responsable del tratamiento"><p><strong>{legalConfig.responsibleName}</strong>, con domicilio en {legalConfig.address}, es responsable del tratamiento de los datos personales de las personas usuarias de Mi Libreta. El contacto de privacidad es <strong>{legalConfig.privacyEmail}</strong>.</p></LegalSection>
    <LegalSection title="2. Datos que tratamos"><ul><li>Cuenta e identidad: nombre, correo, fotografía de perfil cuando se usa Google, identificador de Firebase y datos de autenticación.</li><li>Negocio y libreta: nombre comercial, giro, teléfono, configuración, administradores y personas invitadas.</li><li>Información ingresada por la persona usuaria: clientes, teléfonos, direcciones, notas, pedidos, fiados, apartados, abonos y movimientos de caja.</li><li>Suscripción: identificadores de cliente y suscripción, estado, periodos y eventos de cobro. Stripe procesa directamente los datos completos de la tarjeta; Mi Libreta no los almacena.</li><li>Datos técnicos y de seguridad: dirección IP, tipo de dispositivo, registros de acceso, errores y actividad necesaria para proteger y operar el servicio.</li></ul><p>Mi Libreta no solicita datos personales sensibles. Evita registrarlos en campos de notas salvo que sean indispensables y cuentes con una base legal adecuada.</p></LegalSection>
    <LegalSection title="3. Finalidades primarias"><ul><li>Crear y autenticar la cuenta, recuperar el acceso y administrar sesiones.</li><li>Prestar, sincronizar, respaldar y proteger las funciones de las libretas.</li><li>Gestionar permisos, invitaciones y administradores de cada libreta.</li><li>Procesar pruebas, suscripciones, facturación, cancelaciones y soporte.</li><li>Prevenir fraude, abuso y usos que comprometan la seguridad.</li><li>Cumplir obligaciones contractuales, fiscales y legales aplicables.</li></ul><p>Actualmente no utilizamos tus datos para publicidad conductual ni vendemos datos personales.</p></LegalSection>
    <LegalSection title="4. Datos de clientes que ingresas"><p>La persona o negocio que crea una libreta decide qué información de sus propios clientes registra y para qué la utiliza. Por ello, esa persona o negocio es responsable de contar con la autorización o base legal necesaria, proporcionar su propio aviso de privacidad y atender los derechos de sus clientes. Mi Libreta actúa como proveedor tecnológico y trata esa información siguiendo las instrucciones de quien administra la libreta.</p></LegalSection>
    <LegalSection title="5. Proveedores y transferencias"><p>Para operar el servicio utilizamos proveedores que pueden tratar información dentro o fuera de México: Google Firebase para autenticación y base de datos; Amazon Web Services para funciones y, cuando se configura, correo; y Stripe para pagos y suscripciones. Estos proveedores actúan conforme a sus contratos y políticas de privacidad.</p><p>También podremos comunicar información cuando una autoridad competente lo requiera, para proteger derechos o seguridad, o como parte de una reestructura corporativa permitida por la ley. Cuando una transferencia requiera consentimiento, lo solicitaremos previamente.</p></LegalSection>
    <LegalSection title="6. Conservación y seguridad"><p>Conservamos los datos mientras la cuenta o la relación contractual permanezca activa y después durante los plazos necesarios para obligaciones legales, defensa de reclamaciones y prevención de fraude. Cuando dejan de ser necesarios, se bloquean y eliminan conforme a los plazos aplicables.</p><p>Aplicamos medidas administrativas y técnicas razonables, como autenticación, reglas de acceso por libreta, conexiones cifradas y separación de permisos. Ningún sistema es infalible; si una vulneración afecta significativamente tus derechos, te informaremos conforme a la ley.</p></LegalSection>
    <LegalSection title="7. Derechos ARCO y revocación"><p>Puedes solicitar acceso, rectificación, cancelación u oposición al tratamiento de tus datos, así como revocar tu consentimiento o limitar su uso, escribiendo a <strong>{legalConfig.privacyEmail}</strong>.</p><p>Incluye tu nombre, un medio para recibir respuesta, documentos para acreditar identidad, la descripción de los datos y el derecho que deseas ejercer. Responderemos en un máximo de 20 días hábiles y, si procede, haremos efectivo el derecho dentro de los 15 días hábiles siguientes. Estos plazos pueden ampliarse una vez cuando exista justificación legal.</p></LegalSection>
    <LegalSection title="8. Cambios al aviso"><p>Los cambios se publicarán en esta misma dirección. Si afectan de forma sustancial las finalidades o requieren nuevo consentimiento, también los comunicaremos por el correo de la cuenta o dentro de la aplicación.</p></LegalSection>
  </LegalLayout>
}
