import { LegalLayout, LegalSection } from '../components/LegalLayout'
import { legalConfig } from '../lib/legal'

export function Terms() {
  return <LegalLayout eyebrow="Condiciones del servicio" title="Términos de uso" summary="Estas reglas describen cómo puedes utilizar Mi Libreta y qué puedes esperar del servicio.">
    <LegalSection title="1. Aceptación y proveedor"><p>Mi Libreta es ofrecida por <strong>{legalConfig.responsibleName}</strong>, RFC {legalConfig.taxId}, con domicilio en {legalConfig.address}. Al crear una cuenta o utilizar el servicio aceptas estos términos y el aviso de privacidad. Si actúas por un negocio, declaras tener facultades para obligarlo.</p></LegalSection>
    <LegalSection title="2. El servicio"><p>Mi Libreta ayuda a registrar clientes, fiados, apartados, pedidos y movimientos de caja. No es un servicio bancario, contable, fiscal, de cobranza ni de asesoría profesional; sus registros no sustituyen comprobantes fiscales ni la contabilidad exigida por las autoridades.</p></LegalSection>
    <LegalSection title="3. Cuenta y seguridad"><ul><li>Debes proporcionar información correcta y mantenerla actualizada.</li><li>Eres responsable de proteger tus credenciales y de la actividad realizada desde tu cuenta.</li><li>Debes avisar a {legalConfig.supportEmail} si detectas acceso no autorizado.</li><li>Debes tener al menos 18 años y capacidad legal para contratar.</li></ul></LegalSection>
    <LegalSection title="4. Libretas, pruebas y administradores"><p>Cada libreta tiene datos, administradores y suscripción independientes. Cada libreta nueva recibe la prueba mostrada al registrarla. Una cuenta puede crear hasta dos libretas propias sin una suscripción activa; cuando al menos una libreta propia tiene una suscripción activa, puede crear adicionales. Las libretas recibidas por invitación no consumen ese límite.</p><p>Quien invita a otra persona es responsable de verificar su identidad y permisos. Los administradores invitados podrán consultar y modificar la información de esa libreta.</p></LegalSection>
    <LegalSection title="5. Suscripciones"><p>El precio, moneda, impuestos, periodicidad y fecha de cobro se muestran antes de confirmar la compra en Stripe. Cada suscripción se renueva automáticamente hasta que se cancela. Al confirmar el pago autorizas expresamente los cobros recurrentes informados en el proceso de compra.</p><p>Consulta la <a href="/pagos-y-cancelaciones">política de pagos y cancelaciones</a> para conocer la prueba, renovación, cancelación y reembolsos.</p></LegalSection>
    <LegalSection title="6. Tu información y la de tus clientes"><p>Conservas la titularidad de la información que ingresas. Nos autorizas a alojarla, respaldarla y procesarla únicamente para prestar y proteger el servicio. Eres responsable de que el contenido sea lícito, exacto y de contar con los avisos y consentimientos necesarios de tus clientes, especialmente cuando registres teléfonos o información patrimonial.</p></LegalSection>
    <LegalSection title="7. Uso permitido"><p>No puedes usar Mi Libreta para cometer fraude, acosar, realizar cobros ilegales, vulnerar derechos, introducir código malicioso, intentar acceder a otras libretas, eludir límites del servicio ni revender el acceso sin autorización. Podemos restringir o suspender cuentas ante riesgos de seguridad, impago o incumplimientos, procurando avisar cuando sea posible.</p></LegalSection>
    <LegalSection title="8. Disponibilidad y respaldos"><p>Trabajamos para mantener el servicio disponible y seguro, pero puede haber interrupciones por mantenimiento, proveedores o causas fuera de nuestro control. La persona usuaria debe conservar los comprobantes originales que resulten necesarios para su negocio y revisar periódicamente la exactitud de sus registros.</p></LegalSection>
    <LegalSection title="9. Propiedad intelectual"><p>La marca, diseño, software y contenidos propios de Mi Libreta pertenecen a su titular o licenciantes. Te otorgamos un derecho limitado, personal, revocable y no transferible para usar el servicio mientras cumplas estos términos.</p></LegalSection>
    <LegalSection title="10. Terminación y responsabilidad"><p>Puedes dejar de usar el servicio y solicitar la eliminación de tu cuenta. Algunas obligaciones y registros podrán conservarse durante los plazos legales. En la medida permitida por la ley, Mi Libreta no responde por decisiones comerciales tomadas exclusivamente con base en datos incorrectos ingresados por la persona usuaria ni por servicios de terceros; nada de esto limita derechos irrenunciables de las personas consumidoras.</p></LegalSection>
    <LegalSection title="11. Contacto y ley aplicable"><p>Para soporte, aclaraciones o reclamaciones escribe a {legalConfig.supportEmail} o llama al {legalConfig.phone}. Estos términos se rigen por las leyes de México. Las controversias se atenderán ante las autoridades competentes de {legalConfig.jurisdiction}, sin limitar los derechos de acudir a la Procuraduría Federal del Consumidor cuando corresponda.</p></LegalSection>
  </LegalLayout>
}
